### ISSUE TITLE
sorry for posting here

### ISSUE THREAD

**Issue by LorenzoPanico** [PyPatel/Machine-Learning-and-AI-in-Trading#1]
Hi, sorry but there was no other way to contact you, please add you email somewhere
i was looking for options strategy then i saw this, which i tried months ago but ended up with nothing but bad predictions

"If anyone here is interested, Contact me." 
does this mean that you could send it in private?

lorenzopanico5@gmail.com

**Comment by PyPatel** [comment]
**It's done..!**  You can contact me through LinkedIn or Email. 
Thanks for pointing it out.
